### ISSUE TITLE
Not being able to add a list in Hangul language while being able to add an item in Hangul

### ISSUE THREAD

**Issue by homokimchi** [nextcloud/tasks#148]
### Steps to reproduce
Trying to add a list with the name '테스트' (, which means test, encoding)
(the encoding of os, db and client is utf-8 over all the system)

### Expected behaviour
Being able to see the list with name '테스트'

### Actual behaviour
Not being able to see the change.

### Server configuration
**Operating system**:
linux, gentoo based

**Web server:**
nginx-1.12.2

**Database:**
postgresql-10.0

**PHP version:**
php-7.2

**Nextcloud version:** (see Nextcloud admin page)
nextcloud-13.0

**Tasks version:** (see Nextcloud apps page)
tasks-0.9.6

**Updated from an older Nextcloud or fresh install:**
updated from 12.0

**Signing status:**

clear

**List of activated apps:**

The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - dav: 1.4.6
  - deck: 0.3.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - theming
  - user_external
  - user_ldap

**Nextcloud configuration:**

nothing interesting

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome

**Operating system:**
osx

**CalDAV-clients:**

#### Web server error log

- access log
221.163.149.51 - - [19/Feb/2018:20:22:11 +0900] "MKCALENDAR /cloud/remote.php/dav/calendars/user// HTTP/1.1" 405 734 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" "-"
- erroor log
nothing

#### Nextcloud log (data/nextcloud.log)

It does not occurs when the name is in English. But it occurs everytime trying in Hangul.

{"reqId":"jYuwLH48rcLza0I2LA2i","level":4,"time":"2018-02-19T11:08:27+00:00","remoteAddr":"221.163.149.51","user":"user","app":"webdav","method":"MKCALENDAR","url":"\/cloud\/remote.php\/dav\/calendars\/user\/\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Message\":\"The resource you tried to create already exists\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(303): Sabre\\\\DAV\\\\Server->createCollection('calendars\\\/uer...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\CalDAV\\\\Plugin->httpMkCalendar(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCALEND...', Array)\\n#4 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/www.tu...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/www.example.com\\\/htdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1181}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"13.0.0.14"}

#### Browser log

core.js?v=b56fa7e2:5729 MKCALENDAR https://www.example.com/cloud/remote.php/dav/calendars/user// 405 (Method Not Allowed)
  request @ core.js?v=b56fa7e2:5729
  create @ merged.js?v=b56fa7e2:1978
  e.add @ merged.js?v=b56fa7e2:1978
  _$scope.create @ merged.js?v=b56fa7e2:1977
  fn @ VM1207:4
  b @ merged.js?v=b56fa7e2:125
  e @ merged.js?v=b56fa7e2:272
  $eval @ merged.js?v=b56fa7e2:144
  $apply @ merged.js?v=b56fa7e2:145
  (anonymous) @ merged.js?v=b56fa7e2:272
  dispatch @ core.js?v=b56fa7e2:3
  r.handle @ core.js?v=b56fa7e2:3
merged.js?v=b56fa7e2:1979 Uncaught (in promise) TypeError: Cannot read property 'uri' of undefined
    at n.add (merged.js?v=b56fa7e2:1979)
    at merged.js?v=b56fa7e2:1978
    at <anonymous>

**Comment by raimund-schluessler** [comment]
This is very likely a server issue. The error reported in the Nextcloud log happens in the CalDAV server code, which is built into Nextcloud server. Please report the issue there: https://github.com/nextcloud/server/issues and link it here. Thanks!

**Comment by homokimchi** [comment]
for the record.
@raimund-schluessler , you are right.

the request function calls _suggestUri() which replaces my '테스트' to '테스트'.toString().toLowerCase().replace(/\s+/g, "-").replace(/[^\w\-]+/g, "").replace(/\-\-+/g, "-").replace(/^-+/, "").replace(/-+$/, "");

In short, '테스트'.toString().toLowerCase().replace(/\s+/g, "-").replace(/[^\w\-]+/g, "") is ""
I'll file a report to the server side.

**Comment by homokimchi** [comment]
@raimund-schluessler , my debbug says

the request function calls _suggestUri() which replaces my '테스트' to '테스트'.toString().toLowerCase().replace(/\s+/g, "-").replace(/[^\w\-]+/g, "").replace(/\-\-+/g, "-").replace(/^-+/, "").replace(/-+$/, "");

In short, '테스트'.toString().toLowerCase().replace(/\s+/g, "-").replace(/[^\w\-]+/g, "") is ""

**Comment by raimund-schluessler** [comment]
Hm, you are right, sorry for my hasty conclusion and thanks for debugging this!

Checking if `suggestUri` is empty and replacing it in this case like the calendar app does it https://github.com/nextcloud/calendar/blob/master/js/app/utility/stringUtility.js#L49-L51 might already be enough.

As a workaround, you can create a calendar with korean names using the calendar app.

**Comment by homokimchi** [comment]
I've learned with this. The pleasure is all mine. Thanks :-)

**Comment by ToKaTpoHb** [comment]
Creating new list in Russian language not working either.

**Comment by raimund-schluessler** [comment]
Will be fixed in the https://github.com/nextcloud/tasks/tree/vue branch
