### ISSUE TITLE
Trash Bin doesn't open

### ISSUE THREAD

**Issue by DedRoller** [nextcloud/tasks#2609]
### Steps to reproduce

1. Have an all-day event in your trash bin
2. Click on "Trash Bin" button in Tasks

```
PRODID:-//IDN nextcloud.com//Calendar app 5.1.0-beta.2//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20250120T213924Z
DTSTAMP:20250120T213933Z
LAST-MODIFIED:20250120T213933Z
SEQUENCE:2
UID:ca513bbb-543a-4609-88da-d2b4bd3487d4
DTSTART;VALUE=DATE:20250120
DTEND;VALUE=DATE:20250121
STATUS:CONFIRMED
SUMMARY:test event
END:VEVENT
END:VCALENDAR
```

### Expected behavior

The trash bin interface should open

### Actual behaviour

Entire interface become grey and inactive. Quit from greyed interface is possible only with refresh tab.

### Tasks app version

0.16.0

### CalDAV-clients used

-

### Browser

Firefox 127.0.1

### Client operating system

Windows, Manjaro

### Server operating system

Debian

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

29.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### Browser log

```Text
TypeError: this.component is null
    _ensureCoverage https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    utcOffset https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    utcOffset https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    toUnixTime https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    toJSDate https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    get jsDate https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    get https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    a https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    items https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    effect https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    run https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    get value https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    get https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    default https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    r https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    Tt https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    default https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    r https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    setup https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    o4 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    ie https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    run https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    update https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    ua https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    nA https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    promise callback*rA https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    $h https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    effect https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    Hh https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    fr https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    set https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    set https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    onShow https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    r https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    ua https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    r0 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    Y9 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    onClick https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    onClick https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    ua https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    r0 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    u https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
store-DE2z1cMA.mjs:2:15555
    N9 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    kc https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    o4 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    ie https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    run https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    update https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    ua https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    nA https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    (Asyncronous: promise callback)
    rA https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    $h https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    effect https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    Hh https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    fr https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    set https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    set https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    onShow https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    r https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    ua https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    r0 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    Y9 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    onClick https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    onClick https://<my_nc_domain>/apps/tasks/js/tasks-main.mjs?v=f21fb9c7-87:2
    ua https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    r0 https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
    u https://<my_nc_domain>/apps/tasks/js/store-DE2z1cMA.mjs:2
```

**Comment by raimund-schluessler** [comment]
I can reproduce it. Thanks for the report.

**Comment by nRaecheR** [comment]
Is there any way to clear the trash bin from the command line (occ) or without this dialog?

We've a task that has been duplicated (another bug?) and can't be deleted because it is already in the trash bin.

**Comment by tamas646** [comment]
Hi! I have the same problem.

@nRaecheR task deletion issues used to be earlier too. See [server/#37577](https://github.com/nextcloud/server/issues/37577).
And I still experience duplication/deletion problems but now without sync errors. I think it's another bug.
If I have time I will file a new issue or update the previous issue in the server repository.

**Comment by tamas646** [comment]
@nRaecheR you can clear the trash bin from the Calendar app. They share a common database.

**Comment by raimund-schluessler** [comment]
For some reason I cannot reproduce the issue anymore. There was a server update to 29.0.4 in the meantime, but I don't know whether this is the reason.

**Comment by DedRoller** [comment]
Hm, i have updated my server to 29.0.4, but issue is reproducing in my case.

**Comment by raimund-schluessler** [comment]
It could also be, that a certain, maybe broken task causes this issue, which got deleted on my instance after the 30 days retention period.

**Comment by raimund-schluessler** [comment]
@DedRoller I tried to guess a fix based on the log report above. It could be that `toJSDate` is the problem. An attempt to work around this is in #2637. I built and packed a version of Tasks including this fix, please find it here: [tasks.tar.gz](https://github.com/user-attachments/files/16501909/tasks.tar.gz)

It would be good if you could test if this fixes the issue for you. Thanks a lot!

**Comment by ostasevych** [comment]
> @DedRoller I tried to guess a fix based on the log report above. It could be that `toJSDate` is the problem. An attempt to work around this is in #2637. I built and packed a version of Tasks including this fix, please find it here: [tasks.tar.gz](https://github.com/user-attachments/files/16501909/tasks.tar.gz)
> 
> It would be good if you could test if this fixes the issue for you. Thanks a lot!

#2637 doesn't fix the trash bin not working

**Comment by raimund-schluessler** [comment]
@ostasevych Could you please show the browser log when trying to open the trash bin?

**Comment by ostasevych** [comment]
> @ostasevych Could you please show the browser log when trying to open the trash bin?

```
JQMIGRATE: Migrate is installed, version 3.4.1
session-heartbeat.js:154 session heartbeat disabled
store-BAR8kSTD.mjs:4342 vobjects loaded {vobjects: Array(2)}
store-BAR8kSTD.mjs:2 TypeError: Cannot read properties of null (reading 'getAllSubcomponents')
    at Proxy._ensureCoverage (store-BAR8kSTD.mjs:487:9589)
    at Proxy.utcOffset (store-BAR8kSTD.mjs:487:8306)
    at Proxy.utcOffset (store-BAR8kSTD.mjs:487:17606)
    at Proxy.toUnixTime (store-BAR8kSTD.mjs:487:19468)
    at Proxy.toJSDate (store-BAR8kSTD.mjs:487:18249)
    at get jsDate (store-BAR8kSTD.mjs:487:86275)
    at Reflect.get (<anonymous>)
    at NA.get (store-BAR8kSTD.mjs:2:8061)
    at tasks-main.mjs?v=ae27179c-95:5:8320
    at Array.map (<anonymous>)
AM @ store-BAR8kSTD.mjs:2
od @ store-BAR8kSTD.mjs:2
x4 @ store-BAR8kSTD.mjs:2
le @ store-BAR8kSTD.mjs:2
run @ store-BAR8kSTD.mjs:2
Ee.M.update @ store-BAR8kSTD.mjs:2
fa @ store-BAR8kSTD.mjs:2
UA @ store-BAR8kSTD.mjs:2
Promise.then
HA @ store-BAR8kSTD.mjs:2
_p @ store-BAR8kSTD.mjs:2
(anonymous) @ store-BAR8kSTD.mjs:2
mp @ store-BAR8kSTD.mjs:2
Rr @ store-BAR8kSTD.mjs:2
set @ store-BAR8kSTD.mjs:2
set @ store-BAR8kSTD.mjs:2
onShow @ tasks-main.mjs?v=ae27179c-95:5
await in onShow
u.<computed>.u.<computed> @ store-BAR8kSTD.mjs:2
fa @ store-BAR8kSTD.mjs:2
p0 @ store-BAR8kSTD.mjs:2
m5 @ store-BAR8kSTD.mjs:2
onClick @ tasks-main.mjs?v=ae27179c-95:2
onClick @ tasks-main.mjs?v=ae27179c-95:2
fa @ store-BAR8kSTD.mjs:2
p0 @ store-BAR8kSTD.mjs:2
u @ store-BAR8kSTD.mjs:2
```

**Comment by raimund-schluessler** [comment]
Thanks for the report. It seems a function internal to a dependency we use (`ical.js`) fails. Could you please try again with this version of Tasks: [tasks.tar.gz](https://github.com/user-attachments/files/16502886/tasks.tar.gz)

I bumped `ical.js` to the latest version, maybe that fixes the problem.

**Comment by ostasevych** [comment]
> Thanks for the report. It seems a function internal to a dependency we use (`ical.js`) fails. Could you please try again with this version of Tasks: [tasks.tar.gz](https://github.com/user-attachments/files/16502886/tasks.tar.gz)
> 
> I bumped `ical.js` to the latest version, maybe that fixes the problem.

Nothing changed :(
[nc_tasks-1722896202087.log](https://github.com/user-attachments/files/16503242/nc_tasks-1722896202087.log)

**Comment by raimund-schluessler** [comment]
I am a bit out ouf ideas what causes this issue, especially, since I cannot reproduce it on my instances (anymore). I could pack a debug version of the Tasks app, that might give some more meaningful error log messages. @ostasevych would you be ok to try such a version on your server? It won't be functionally different from the standard version, the files are just not compressed, so the loading times are a bit higher.

**Comment by ostasevych** [comment]
> I am a bit out ouf ideas what causes this issue, especially, since I cannot reproduce it on my instances (anymore). I could pack a debug version of the Tasks app, that might give some more meaningful error log messages. @ostasevych would you be ok to try such a version on your server? It won't be functionally different from the standard version, the files are just not compressed, so the loading times are a bit higher.

Send me the file, please.

**Comment by DedRoller** [comment]
> @DedRoller Can you open the trash bin in the Calendar app?

Yeah, i've cleared trash bin from callendar app, and tasks bin is working now! Thanks)

**Comment by raimund-schluessler** [comment]
> > @DedRoller Can you open the trash bin in the Calendar app?
> 
> Yeah, i've cleared trash bin from callendar app, and tasks bin is working now! Thanks)

Hm, so it seems to be a certain task, that crashes the trash bin. Would be good to know what property leads to the issue.

**Comment by raimund-schluessler** [comment]
> > > > @DedRoller Can you open the trash bin in the Calendar app?
> > > 
> > > 
> > > Yeah, i've cleared trash bin from callendar app, and tasks bin is working now! Thanks)
> > 
> > 
> > Hm, so it seems to be a certain task, that crashes the trash bin. Would be good to know what property leads to the issue.
> 
> Hi! I have identified the reason - it is about your availability.
> 
>     * go to your personal settings
> 
>     * add your absence time slot
> 
>     * delete it
> 
>     * find it in the calendar trash bin
> 
>     * check that the tasks trash bin is not working
> 
>     * delete the availability item from the calendar trash bin
> 
>     * check that the task trash bin is working

You mean this?
![grafik](https://github.com/user-attachments/assets/ae0aa173-1ae7-44e8-af8f-ef2e02c310cc)

Deleting / deactivating does not generate a trash bin entry for me.

**Comment by ostasevych** [comment]
> > > > > @DedRoller Can you open the trash bin in the Calendar app?
> > > > 
> > > > 
> > > > Yeah, i've cleared trash bin from callendar app, and tasks bin is working now! Thanks)
> > > 
> > > 
> > > Hm, so it seems to be a certain task, that crashes the trash bin. Would be good to know what property leads to the issue.
> > 
> > 
> > Hi! I have identified the reason - it is about your availability.
> > ```
> > * go to your personal settings
> > 
> > * add your absence time slot
> > 
> > * delete it
> > 
> > * find it in the calendar trash bin
> > 
> > * check that the tasks trash bin is not working
> > 
> > * delete the availability item from the calendar trash bin
> > 
> > * check that the task trash bin is working
> > ```
> 
> You mean this? ![grafik](https://private-user-images.githubusercontent.com/2496460/355703028-ae0aa173-1ae7-44e8-af8f-ef2e02c310cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzE0NzksIm5iZiI6MTcyMzAzMTE3OSwicGF0aCI6Ii8yNDk2NDYwLzM1NTcwMzAyOC1hZTBhYTE3My0xYWU3LTQ0ZTgtYWY4Zi1lZjJlMDJjMzEwY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTE0NjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QxYzMzMzgwN2E3N2MzZWRkZjRkMzI2ZmRhNDJiNzAwZDJjODM1MzYxMDY3NzY4YTI4YjA0NTZiNGFiZjYzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RIsIgq3irOQ33i4ftqk67qJLps8UPmzbAs_BKhlDZ0g)
> 
> Deleting / deactivating does not generate a trash bin entry for me.

Yes, exactly this one. For me it worked... However, I didn't have other items in the trash bin. So, probably it is about emptying it in general 🤔

**Comment by raimund-schluessler** [comment]
I can now reproduce it (again). Having an all-day *event* in the trash bin triggers the issue. It does not happen for all-day tasks, though.

**Comment by Sarmingsteiner** [comment]
Trash bin, accessed through *Tasks*, still freezes in Nextcloud 30.0.2 when it contains items; it only works smoothly when empty.

**Comment by tamas646** [comment]
I still experience this issue. 

<details>

<summary>Javascript error (same as above):</summary>

```js
TypeError: this.component is null
    _ensureCoverage https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:497
    utcOffset https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:497
    utcOffset https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:493
    toUnixTime https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:493
    compare https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:493
    next https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:497
    _expandComponent https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:497
    _ensureCoverage https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:497
    utcOffset https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:497
    utcOffset https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:493
    toUnixTime https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:493
    toJSDate https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:493
    get jsDate https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:4355
    get https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    a https://<my-nc-domain>/apps/tasks/js/tasks-main.mjs?v=d869bc3b-35:5
    items https://<my-nc-domain>/apps/tasks/js/tasks-main.mjs?v=d869bc3b-35:5
    effect https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    run https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    get value https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    get https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    default https://<my-nc-domain>/apps/tasks/js/tasks-main.mjs?v=d869bc3b-35:5
    a https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Tt https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    default https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:502
    a https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    setup https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Hh https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    re https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    run https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    update https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Zr https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Kv https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    promise callback*Jv https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Q1 https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    effect https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    U1 https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    rr https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    set https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    set https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    onShow https://<my-nc-domain>/apps/tasks/js/tasks-main.mjs?v=d869bc3b-35:5
    a https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Zr https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    k0 https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    CN https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    onClick https://<my-nc-domain>/apps/tasks/js/tasks-main.mjs?v=d869bc3b-35:2
    onClick https://<my-nc-domain>/apps/tasks/js/tasks-main.mjs?v=d869bc3b-35:2
    Zr https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    k0 https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    u https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Mn https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    nR https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    dR https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    U https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    X https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    y https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    te https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    U https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    X https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    y https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    te https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    H https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    y https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    re https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    run https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    update https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Ee https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    pe https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    he https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    y https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    te https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    U https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    X https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    y https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    re https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    run https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    update https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    Ee https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    pe https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
    he https://<my-nc-domain>/apps/tasks/js/store-BBMiux8F.chunk.mjs:2
store-BBMiux8F.chunk.mjs:2:15517
```

</details>

**Nextcloud version:** 31.0.5
**Tasks app version:** 0.16.1

Maybe there's something weird with my database?

**Comment by tamas646** [comment]
**Update:** I deleted only calendar events from the trash bin, and now it opens correctly in the Tasks app too.

And I see that a fix is already merged but not released. Can this be released maybe? Thanks!

**Comment by oleua** [comment]
I still see the issue with showing the trash bin. It is no more appearing.
